import type { SessionRow } from './queries';

// Parse the categories JSON, with a graceful fallback to the legacy single
// category column for rows that haven't been re-classified yet. Lives here
// (not in queries.ts) so client components can import it without pulling in
// node:fs / node:os transitively via the detection helpers.
export function sessionCategories(
  s: { categories?: string | null; category?: string | null },
): string[] {
  if (s.categories) {
    try {
      const parsed = JSON.parse(s.categories);
      if (Array.isArray(parsed)) return parsed.filter((x): x is string => typeof x === 'string');
    } catch {
      // fall through to legacy
    }
  }
  return s.category ? [s.category] : [];
}

export function displayTitle(s: Pick<SessionRow, 'summary' | 'heuristic_title' | 'first_prompt'>): string {
  if (s.summary) return s.summary.split('\n')[0].trim();
  if (s.heuristic_title) return s.heuristic_title;
  if (s.first_prompt) return titleFromPrompt(s.first_prompt);
  return '(untitled session)';
}

// Known Claude Code preamble patterns that need stripping before we look
// for real prompt content. Kept in sync with isClaudeCodePreamble() in
// the ingester — see that function for the rationale.
const PREAMBLE_PATTERNS: RegExp[] = [
  /<environment_context>[\s\S]*?<\/environment_context>/gi,
  /<command-(?:name|message|args)>[\s\S]*?<\/command-(?:name|message|args)>/gi,
  /<local-command-(?:stdout|stderr|caveat)>[\s\S]*?<\/local-command-(?:stdout|stderr|caveat)>/gi,
  /^Caveat: The messages below were generated by the user while running local commands\.?\s*/i,
];

// Best-effort cleanup of a raw user prompt so it reads as a title in lists.
// Not a replacement for LLM classification — just a friendlier fallback.
export function titleFromPrompt(prompt: string): string {
  let text = prompt.trim();

  // Strip known Claude Code preambles whole (block + content) first.
  for (const p of PREAMBLE_PATTERNS) text = text.replace(p, ' ');
  text = text.trim();

  // Strip remaining Claude/Codex command markers and tags like
  // <command-name>, <local-command-stdout>, etc.
  text = text.replace(/<[^>]+>/g, ' ');
  // Drop leading slash commands ("/compact", "/init", "/help foo") — usually meta.
  text = text.replace(/^\/[a-z][a-z0-9-]*(\s|$)/i, '');
  // Collapse code-fence and inline-code delimiters; keep their contents.
  text = text.replace(/```[a-z]*\n?/gi, ' ').replace(/```/g, ' ').replace(/`/g, '');
  // Strip Markdown link URL parts: "[label](url)" → "label".
  text = text.replace(/\[([^\]]+)\]\([^)]*\)/g, '$1');
  // Drop standalone URLs.
  text = text.replace(/https?:\/\/\S+/g, '');
  // Drop absolute file paths that aren't useful as title material.
  text = text.replace(/(^|\s)(\/|~\/)[\w./~-]+/g, ' ');
  // Collapse whitespace.
  text = text.replace(/\s+/g, ' ').trim();

  // Use the first sentence-ish chunk if it's reasonably short.
  const sentenceEnd = text.search(/[.!?](\s|$)/);
  if (sentenceEnd > 8 && sentenceEnd < 90) {
    text = text.slice(0, sentenceEnd).trim();
  }

  if (text.length === 0) return '(untitled session)';

  // Capitalize first letter for a title-ish feel without forcing Title Case.
  text = text.charAt(0).toUpperCase() + text.slice(1);

  if (text.length <= 90) return text;
  const cut = text.lastIndexOf(' ', 90);
  return (cut > 50 ? text.slice(0, cut) : text.slice(0, 90)) + '…';
}
