import { readdirSync, statSync, createReadStream, existsSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { createInterface } from 'node:readline';
import { randomUUID } from 'node:crypto';
import { getSqlite } from '../db/client';
import { resolveProject, upsertProject } from '../projects';
import { estimateCost } from '../pricing';
import { getSetting } from '../queries';
import { extractToolIo, type ToolIo } from './contentBreakdown';

function walkJsonl(dir: string, out: string[]) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walkJsonl(p, out);
    else if (e.isFile() && e.name.endsWith('.jsonl')) out.push(p);
  }
}

type ClaudeLine = {
  type: string;
  uuid?: string;
  parentUuid?: string | null;
  sessionId?: string;
  timestamp?: string;
  cwd?: string;
  gitBranch?: string;
  message?: {
    role?: string;
    content?: unknown;
    model?: string;
    usage?: {
      input_tokens?: number;
      output_tokens?: number;
      cache_read_input_tokens?: number;
      cache_creation_input_tokens?: number;
    };
  };
};

function flattenContent(content: unknown): string {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    return content
      .map((c) => {
        if (typeof c === 'string') return c;
        if (c && typeof c === 'object') {
          const o = c as { type?: string; text?: string; content?: unknown };
          if (o.type === 'text' && typeof o.text === 'string') return o.text;
          if (o.type === 'tool_use') return '';
          if (o.type === 'tool_result' && typeof o.content === 'string') return '';
          return '';
        }
        return '';
      })
      .join('\n')
      .trim();
  }
  return '';
}

// Limit-reached events appear in two shapes:
//   1) system message with content like "Claude AI usage limit reached|1780687599"
//   2) tool_result inside a user message with the same string
// Returns the unix epoch reset time, or null if not present.
// (Note: the substring "limit reached" also appears legitimately inside our own
// code/transcripts when discussing rate limits — we *only* match the pipe form
// that carries an explicit timestamp, which Claude uses for real limit events.)
function extractLimitResetTimestamp(text: string): number | null {
  const m = text.match(/limit reached\|(\d{9,11})/);
  if (!m) return null;
  const ts = parseInt(m[1], 10);
  if (!Number.isFinite(ts) || ts < 1_600_000_000) return null;
  return ts;
}

function scanContentForLimit(content: unknown): number | null {
  if (typeof content === 'string') return extractLimitResetTimestamp(content);
  if (Array.isArray(content)) {
    for (const c of content) {
      if (typeof c === 'string') {
        const r = extractLimitResetTimestamp(c);
        if (r) return r;
      } else if (c && typeof c === 'object') {
        const o = c as { type?: string; text?: string; content?: unknown };
        if (typeof o.text === 'string') {
          const r = extractLimitResetTimestamp(o.text);
          if (r) return r;
        }
        // tool_result.content can itself be a string or an array of text parts.
        if (o.type === 'tool_result') {
          const r = scanContentForLimit(o.content);
          if (r) return r;
        }
      }
    }
  }
  return null;
}

// Claude Code injects several plain-text messages into the user-side of
// the transcript that aren't actually things the user typed:
//   - <environment_context> blocks describing the working dir / git state.
//   - <command-name>, <command-message>, <command-args> stubs from slash
//     commands like /init, /compact.
//   - <local-command-stdout>, <local-command-stderr>, <local-command-caveat>
//     blocks wrapping shell-command output (the "caveat" one carries the
//     well-known "Caveat: The messages below were generated by the user
//     while running local commands" preamble).
// None of these should ever land as the session's first prompt or first
// user message.
export function isClaudeCodePreamble(text: string): boolean {
  if (text.startsWith('<environment_context>')) return true;
  if (text.startsWith('<command-')) return true;
  if (text.startsWith('<local-command-')) return true;
  // Defensive: catches the literal "Caveat:" preamble in case Claude Code
  // ever changes the wrapper tag but keeps the text.
  if (text.startsWith('Caveat: The messages below were generated by the user')) return true;
  return false;
}

export type IngestStats = {
  filesScanned: number;
  filesIngested: number;
  sessions: number;
  messages: number;
};

export async function ingestClaude(opts: { onProgress?: (msg: string) => void } = {}): Promise<IngestStats> {
  const base =
    getSetting('claude_log_dir') ||
    process.env.AGENTGRAPHED_CLAUDE_DIR ||
    process.env.AGENTGRAPH_CLAUDE_DIR ||
    join(homedir(), '.claude', 'projects');
  const stats: IngestStats = { filesScanned: 0, filesIngested: 0, sessions: 0, messages: 0 };

  const files: string[] = [];
  // Layout: <encoded-cwd>/<session-uuid>.jsonl
  if (existsSync(base)) {
    for (const dirent of readdirSync(base, { withFileTypes: true })) {
      if (!dirent.isDirectory()) continue;
      walkJsonl(join(base, dirent.name), files);
    }
  }
  stats.filesScanned = files.length;

  const db = getSqlite();
  const getIngestState = db.prepare('SELECT mtime, size FROM ingest_state WHERE source_path = ?');
  const upsertIngestState = db.prepare(
    'INSERT OR REPLACE INTO ingest_state (source_path, mtime, size, session_id, ingested_at) VALUES (?, ?, ?, ?, ?)',
  );

  for (const file of files) {
    const st = statSync(file);
    const cached = getIngestState.get(file) as { mtime: number; size: number } | undefined;
    if (cached && cached.mtime === Math.floor(st.mtimeMs) && cached.size === st.size) continue;

    try {
      const result = await ingestOneFile(file);
      if (result) {
        upsertIngestState.run(file, Math.floor(st.mtimeMs), st.size, result.sessionId, Date.now());
        stats.filesIngested += 1;
        stats.sessions += 1;
        stats.messages += result.messageCount;
        opts.onProgress?.(`Claude: ${stats.filesIngested}/${files.length}`);
      }
    } catch (e) {
      // skip malformed file
      opts.onProgress?.(`Claude: skipped ${file} (${(e as Error).message})`);
    }
  }
  return stats;
}

async function ingestOneFile(file: string): Promise<{ sessionId: string; messageCount: number } | null> {
  const db = getSqlite();
  const rl = createInterface({ input: createReadStream(file, 'utf8'), crlfDelay: Infinity });

  let sessionId: string | null = null;
  let cwd: string | null = null;
  let gitBranch: string | null = null;
  let startedAt: number | null = null;
  let endedAt: number | null = null;
  let lastModel: string | null = null;
  let messageCount = 0;
  let userMessageCount = 0;
  let inputTokens = 0;
  let outputTokens = 0;
  let cacheRead = 0;
  let cacheWrite = 0;
  let firstPrompt: string | null = null;
  const limitEvents: Array<{ observed_at: number; reset_at: number; kind: string; raw: string }> = [];
  const messages: Array<{
    id: string;
    role: string;
    content: string;
    timestamp: number;
    model: string | null;
    input_tokens: number;
    output_tokens: number;
    cache_read_tokens: number;
    cache_write_tokens: number;
    est_cost_usd: number;
  }> = [];

  // Per-content-item breakdown ("where did this turn's bytes come from?").
  // Buffered per file and flushed in one transaction at the end alongside
  // messages — same idempotency story.
  const toolIoBatch: Array<{
    message_id: string;
    idx: number;
    timestamp: number;
    item: ToolIo;
  }> = [];
  // tool_result items only carry the tool_use_id pointing back at the
  // earlier assistant turn's tool_use. We resolve to the tool name in a
  // single pass at the end so the UI doesn't need a join.
  const toolNameByUseId = new Map<string, string>();
  // We also need to know which tool_use items had IDs so we can write the
  // raw id into source during parsing, and rewrite it on flush.
  const collectToolIo = (
    messageId: string,
    timestamp: number,
    role: string | undefined,
    content: unknown,
    rawItems: unknown,
  ) => {
    const items = extractToolIo(role, content);
    // The parser doesn't see Claude's per-item `id` field; pluck it here so
    // we can populate toolNameByUseId. tool_use items carry `id` + `name`.
    if (Array.isArray(rawItems)) {
      for (const c of rawItems) {
        if (c && typeof c === 'object') {
          const o = c as { type?: string; id?: string; name?: string };
          if (o.type === 'tool_use' && typeof o.id === 'string' && typeof o.name === 'string') {
            toolNameByUseId.set(o.id, o.name);
          }
        }
      }
    }
    items.forEach((item, i) => toolIoBatch.push({ message_id: messageId, idx: i, timestamp, item }));
  };

  for await (const raw of rl) {
    if (!raw.trim()) continue;
    let line: ClaudeLine;
    try {
      line = JSON.parse(raw);
    } catch {
      continue;
    }
    if (line.sessionId && !sessionId) sessionId = line.sessionId;
    if (line.cwd && !cwd) cwd = line.cwd;
    if (line.gitBranch && !gitBranch) gitBranch = line.gitBranch;

    const ts = line.timestamp ? Date.parse(line.timestamp) : NaN;
    if (!Number.isNaN(ts)) {
      if (startedAt === null || ts < startedAt) startedAt = ts;
      if (endedAt === null || ts > endedAt) endedAt = ts;
    }

    // Limit-reached scan applies to both 'user' (tool_result) and 'system' lines.
    if (line.type === 'user' || line.type === 'system') {
      const resetAt = scanContentForLimit(line.message?.content);
      if (resetAt) {
        const observedAt = Number.isNaN(ts) ? Date.now() : ts;
        limitEvents.push({
          observed_at: observedAt,
          reset_at: resetAt * 1000,
          kind: line.type,
          raw: flattenContent(line.message?.content).slice(0, 500),
        });
      }
    }

    if (line.type === 'user' && line.message?.role === 'user') {
      const text = flattenContent(line.message.content);
      // User-side messages are either real prompts OR tool_result echoes
      // (which we still want to count toward tool_result tokens). We persist
      // the message row only for the prompt path, but the breakdown gets
      // collected either way.
      const isToolResultEcho =
        Array.isArray(line.message.content) &&
        line.message.content.some(
          (c) => c && typeof c === 'object' && (c as { type?: string }).type === 'tool_result',
        );
      const msgId = line.uuid || randomUUID();
      // Claude Code injects several preamble messages we don't want surfacing
      // as the session's "first prompt" — env context, slash-command stubs,
      // and the local-command-caveat block that prefaces tool runs.
      if (text && !isClaudeCodePreamble(text)) {
        if (!firstPrompt) firstPrompt = text.slice(0, 500);
        userMessageCount += 1;
        messages.push({
          id: msgId,
          role: 'user',
          content: text,
          timestamp: Number.isNaN(ts) ? Date.now() : ts,
          model: null,
          input_tokens: 0,
          output_tokens: 0,
          cache_read_tokens: 0,
          cache_write_tokens: 0,
          est_cost_usd: 0,
        });
        messageCount += 1;
      }
      // Always collect breakdown so tool_results contribute even when no
      // message row gets persisted for the user line.
      if (isToolResultEcho || text) {
        const lineTs = Number.isNaN(ts) ? Date.now() : ts;
        collectToolIo(msgId, lineTs, 'user', line.message.content, line.message.content);
      }
    } else if (line.type === 'assistant' && line.message) {
      if (line.message.model) lastModel = line.message.model;
      const u = line.message.usage;
      const msgIn = u?.input_tokens || 0;
      const msgOut = u?.output_tokens || 0;
      const msgCacheR = u?.cache_read_input_tokens || 0;
      const msgCacheW = u?.cache_creation_input_tokens || 0;
      if (u) {
        inputTokens += msgIn;
        outputTokens += msgOut;
        cacheRead += msgCacheR;
        cacheWrite += msgCacheW;
      }
      const text = flattenContent(line.message.content);
      const msgId = line.uuid || randomUUID();
      if (text) {
        const msgCost = estimateCost({
          model: line.message.model || lastModel,
          inputTokens: msgIn,
          outputTokens: msgOut,
          cacheReadTokens: msgCacheR,
          cacheWriteTokens: msgCacheW,
        });
        messages.push({
          id: msgId,
          role: 'assistant',
          content: text.slice(0, 4000),
          timestamp: Number.isNaN(ts) ? Date.now() : ts,
          model: line.message.model || null,
          input_tokens: msgIn,
          output_tokens: msgOut,
          cache_read_tokens: msgCacheR,
          cache_write_tokens: msgCacheW,
          est_cost_usd: msgCost,
        });
        messageCount += 1;
      }
      // Capture breakdown even when there's no surfaced text — assistant
      // turns that consist of just a tool_use still contribute to the
      // session's output bytes.
      const lineTs = Number.isNaN(ts) ? Date.now() : ts;
      collectToolIo(msgId, lineTs, 'assistant', line.message.content, line.message.content);
    }
  }

  if (!sessionId || startedAt === null || endedAt === null) return null;
  if (!cwd) cwd = process.cwd();

  const project = resolveProject(cwd);
  upsertProject(project, endedAt);

  const cost = estimateCost({
    model: lastModel,
    inputTokens,
    outputTokens,
    cacheReadTokens: cacheRead,
    cacheWriteTokens: cacheWrite,
  });

  // Preserve any LLM-generated title/category from a prior classification pass.
  const insertSession = db.prepare(`
    INSERT OR REPLACE INTO sessions (
      id, provider, project_id, cwd, started_at, ended_at, duration_ms, model,
      message_count, user_message_count, input_tokens, output_tokens,
      cache_read_tokens, cache_write_tokens, est_cost_usd, first_prompt,
      summary, summary_generated, heuristic_title, category, keywords,
      git_branch, source_path
    ) VALUES (?, 'claude', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
      (SELECT summary FROM sessions WHERE id = ?),
      (SELECT summary_generated FROM sessions WHERE id = ?),
      (SELECT heuristic_title FROM sessions WHERE id = ?),
      (SELECT category FROM sessions WHERE id = ?),
      (SELECT keywords FROM sessions WHERE id = ?),
      ?, ?)
  `);
  insertSession.run(
    sessionId,
    project.id,
    cwd,
    startedAt,
    endedAt,
    endedAt - startedAt,
    lastModel,
    messageCount,
    userMessageCount,
    inputTokens,
    outputTokens,
    cacheRead,
    cacheWrite,
    cost,
    firstPrompt,
    sessionId,
    sessionId,
    sessionId,
    sessionId,
    sessionId,
    gitBranch,
    file,
  );

  // IMPORTANT: do not DELETE-then-INSERT messages per session. Claude Code
  // emits *multiple* JSONL files for the same sessionId — one main transcript
  // plus per-subagent files under <sessionId>/subagents/*.jsonl — and each one
  // gets ingested separately. Wiping by sessionId on every file means the
  // *last* subagent file processed ends up as the only surviving message set
  // for that session. Use upsert keyed on (id) instead: Claude provides
  // stable per-message UUIDs, so each file's messages accumulate correctly
  // into the shared session. On conflict, refresh the token columns from the
  // incoming row — this lets a re-ingest correct earlier 0-token writes
  // (e.g. rows seeded by the prorated backfill that later get a real
  // per-message ingest).
  const insertMessage = db.prepare(
    `INSERT INTO messages (
       id, session_id, role, content, timestamp, model,
       input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, est_cost_usd
     ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(id) DO UPDATE SET
       input_tokens = excluded.input_tokens,
       output_tokens = excluded.output_tokens,
       cache_read_tokens = excluded.cache_read_tokens,
       cache_write_tokens = excluded.cache_write_tokens,
       est_cost_usd = excluded.est_cost_usd`,
  );
  const tx = db.transaction((rows: typeof messages) => {
    for (const m of rows) {
      insertMessage.run(
        m.id, sessionId, m.role, m.content, m.timestamp, m.model,
        m.input_tokens, m.output_tokens, m.cache_read_tokens, m.cache_write_tokens, m.est_cost_usd,
      );
    }
  });
  tx(messages);

  // Persist the content-item breakdown. Keyed on (message_id, idx) so
  // subagent files for the same session accumulate alongside the parent
  // transcript's rows — same lesson as the v3 messages fix. ON CONFLICT
  // refreshes bytes / est_tokens / source so a re-ingest can correct any
  // earlier scan where the tool_use_id → name map was incomplete.
  if (toolIoBatch.length > 0) {
    const insertToolIo = db.prepare(
      `INSERT INTO tool_io (
         message_id, session_id, idx, timestamp, kind, source, bytes, est_tokens
       ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
       ON CONFLICT(message_id, idx) DO UPDATE SET
         timestamp = excluded.timestamp,
         kind = excluded.kind,
         source = excluded.source,
         bytes = excluded.bytes,
         est_tokens = excluded.est_tokens`,
    );
    const ioTx = db.transaction(() => {
      for (const row of toolIoBatch) {
        let source = row.item.source;
        if (row.item.kind === 'tool_result' && source && toolNameByUseId.has(source)) {
          source = toolNameByUseId.get(source)!;
        }
        insertToolIo.run(
          row.message_id, sessionId, row.idx, row.timestamp, row.item.kind, source,
          row.item.bytes, row.item.est_tokens,
        );
      }
    });
    ioTx();
  }

  // Persist any limit-reached events from this session. Wipe-and-rewrite per
  // session keeps it idempotent on re-ingest without needing a composite key.
  db.prepare('DELETE FROM claude_limit_events WHERE session_id = ?').run(sessionId);
  if (limitEvents.length > 0) {
    const insertLimit = db.prepare(
      'INSERT INTO claude_limit_events (session_id, observed_at, reset_at, kind, raw) VALUES (?, ?, ?, ?, ?)',
    );
    const limitTx = db.transaction((rows: typeof limitEvents) => {
      for (const e of rows) insertLimit.run(sessionId, e.observed_at, e.reset_at, e.kind, e.raw);
    });
    limitTx(limitEvents);
  }

  return { sessionId, messageCount };
}
